openapi: 3.0.0
info:
  title: API Ping
  version: "1.0.0"
  description: Une API simple avec une route GET /ping qui retourne "pong".
paths:
  /ping:
    get:
      summary: Vérifie la disponibilité du service
      description: Retourne la chaîne "pong" si l’API est accessible.
      responses:
        '200':
          description: Réponse réussie avec le message pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
